Repository Muskansahuincredible/StudyNotion-An-Online-Education-Platform, pull requests merged in 2024-05, with the labels that each got.

#25 Update 404ErrorPage
  src/assets/Images/404.png
  src/pages/Error.jsx
Labels: enhancement, gssoc, level 2

#30 Created CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: level 1, gssoc

#31 Added "Go-To-Top" Button to the website
  package-lock.json
  package.json
  src/App.js
  src/components/GoToTop.jsx
Labels: gssoc, level 2

#18 Fix Navbar Sticky Behavior When Scrolling #12
  .gitignore
  src/App.css
  src/components/common/Navbar.jsx
Labels: enhancement, level 1, gssoc

#39 Added pull_request_template.md
  .github/pull_request_template.md
Labels: enhancement, level 1, gssoc

#123 Adding hover effect on cards
  src/components/core/HomePage/CourseCard.jsx
Labels: gssoc

#125 Updated README.md
  README.md
Labels: gssoc

#128 Reviews from other leaners card has been designed as even size.
  src/components/common/ReviewSlider.jsx
Labels: gssoc
