Repository Muskansahuincredible/StudyNotion-An-Online-Education-Platform, pull requests merged in 2024-07, with the labels that each got.

#262 NavBar Hover effect updated
  src/App.js
  src/components/common/Navbar.jsx
Labels: enhancement, good first issue, level1, Gssoc

#268 Fix : (Navbar Sticked)
  src/components/common/Navbar.jsx
Labels: enhancement, Gssoc, level3

#270 add counting animation at about us fix issue #265
  src/App.js
  src/components/core/AboutPage/Stats.jsx
  src/components/core/AboutPage/useIntersectionObserver.js
Labels: Gssoc, level2

#274 Made navbar sticky on top
  src/components/common/Navbar.jsx
Labels: enhancement, Gssoc, level2

#278 Instagram and LinkedIn accounts at footer added
  src/components/common/Footer.jsx
Labels: level1, Gssoc

#279 Adding Cursor Animation
  src/App.css
  src/assets/Images/ads_click_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24 (2).svg
Labels: Gssoc, level2

#283 Navbar hover styles
  src/components/common/Navbar.jsx
Labels: Gssoc, level2

#284 Rate us navbar
  src/components/common/Navbar.jsx
  src/data/navbar-links.js
Labels: Gssoc, level2

#259 Added project section
  .vscode/settings.json
  package-lock.json
  package.json
  src/App.js
  src/assets/Images/image1.png
  src/assets/Images/image2.jpg
  src/assets/Images/image3.webp
  src/assets/Images/image4.jpg
  src/assets/Images/image5.jpg
  src/assets/Images/image6.jpg
  src/assets/Images/image7.jpeg
  src/assets/Images/image8.webp
  src/assets/Images/image9.webp
  src/components/core/AboutPage/LearningGrid.jsx
  src/components/core/HomePage/Button.jsx
  src/data/navbar-links.js
  src/pages/About.jsx
  src/pages/Project.jsx
Labels: Gssoc, level3

#286 Navbar made sticky
  src/components/common/Navbar.jsx
  src/index.css
Labels: Gssoc, level3

#287 I did changes in contact section
  src/components/ContactPage/ContactDetails.jsx
Labels: level1, Gssoc

#351 solved footer issue
  src/data/footer-links.js
Labels: level1, Gssoc

#355 Added some spacing between the elements in the navbar.
  src/components/common/Navbar.jsx
Labels: Gssoc, level2
